services:
    config_service:
        image: service
        build:
            context: ..
            dockerfile: service.Dockerfile
        ports:
            - "9090:9090"
        networks:
            - net
        depends_on:
            - mongo
        command: bash -c "java -jar /home/Service/target/ConfigurationService-1.0-jar-with-dependencies.jar"
    mongo:
        image: mongo:latest
        container_name: mongo
        restart: always
        command: mongod --port 27018
        ports:
            - "27018:27018"
        networks:
            - net

networks:
    net:
        driver: bridge